### ISSUE TITLE
TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by Fansgithub2019** [rafaelvalle/asrgen#3]
‘python python gan_train.py ’
An error has occurred

  File "<ipython-input-9-da56cefe6db9>", line 1, in <module>
    runfile('D:/Documents/paper/asrgen-master/asrgen-master/gan_train.py', wdir='D:/Documents/paper/asrgen-master/asrgen-master')

  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Documents/paper/asrgen-master/asrgen-master/gan_train.py", line 140, in <module>
    logger.log_validation(real_data_spk, real_data_spk+reg_noise,fake_data, iteration)

  File "D:\Documents\paper\asrgen-master\asrgen-master\logger.py", line 33, in log_validation
    iteration)

  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\tensorboardX\writer.py", line 548, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)

  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\tensorboardX\summary.py", line 216, in image
    image = make_image(tensor, rescale=rescale)

  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\tensorboardX\summary.py", line 256, in make_image
    image = Image.fromarray(tensor)

  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\PIL\Image.py", line 2492, in fromarray
    raise TypeError("Cannot handle this data type")

TypeError: Cannot handle this data type

How can I fix it ?

**Comment by rafaelvalle** [comment]
This probably has to do with the version of tensorboardX you're using.

**Comment by Fansgithub2019** [comment]
Thank you for your reply.
I solved this problem by going through line 30 in logger.py

Convert
Self.add_image("mel_real",Plot_spectrogram_to_numpy(mel_real, 6, 5), Iteration)
Into
Self.add_image("mel_real", Plot_spectrogram_to_numpy(mel_real, 6, 5), Iteration,dataformats='HWC')

Add the parameter dataformats='HWC' and change the tensor format to "HWC" because add_image defaults to "CHW".
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
There is another problem: when running gan_attack.ipynb
appear
RuntimeError Traceback (most recent call last)
<ipython-input-20-e5ef39be39a2> in <module>
      4 N_CLASSES = 102
      5 SR_model = SpeakerRecognitionModel(N_CLASSES)
----> 6 SR_model.load_state_dict(torch.load(sr_path, map_location='cpu')['model'])

D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py in load_state_dict(self, state_dict, strict)
    775 if len(error_msgs) > 0:
    776 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 777 self.__class__.__name__, "\n\t".join(error_msgs)))
    778 return _IncompatibleKeys(missing_keys, unexpected_keys)
    779

RuntimeError: Error(s) in loading state_dict for SpeakerRecognitionModel:
Size mismatch for linears.2.weight: copying a param with shape torch.Size([101, 256]) from checkpoint, the shape in current model is torch.Size([102, 256]).
Size mismatch for linears.2.bias: copying a param with shape torch.Size([101]) from checkpoint, the shape in current model is torch.Size([102]).
Just change N_CLASSES = 102 to N_CLASSES = 101 and the error disappears. But the result is that Attack accuracy 90.4296875% is not as 97% as your result.
Can you help me with my doubts?

**Comment by Fansgithub2019** [comment]
Maybe the model training is not enough.

**Comment by rafaelvalle** [comment]
> Maybe the model training is not enough.

Is this a different issue?

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
